### ISSUE TITLE
SMTP login fails when using TLS

### ISSUE THREAD

**Issue by eLBati** [openlabs/poweremail#1]
Steps:

Create a new account and set "Use TLS" only.
Click con "Check Outgoing Connection"
Exception is raised: "character mapping must return integer, None or unicode"

This is actually raised by smtplib and I solved replacing line 258 of poweremail_core.py with
serv.login(str(this_object.smtpuname), str(this_object.smtppass))

**Comment by sharoonthomas** [comment]
Hi

I have fixed this issue in the dev branch, can you confirm if the fix works for you ?

_Remember that this is not the main branch_

git clone git://github.com/openlabs/poweremail.git
git checkout dev

**Comment by eLBati** [comment]
Hello sharoon,
it works for me.

(In order to install the module from dev branch, I had to replace line 33 of send_wizard.py with
from template import get_value
)
