### ISSUE TITLE
smtppass must be visible

### ISSUE THREAD

**Issue by ferdinandg** [openlabs/poweremail#14]
diff --git a/poweremail_core.py b/poweremail_core.py
index 4fd7de8..3726e41 100644
--- a/poweremail_core.py
+++ b/poweremail_core.py
@@ -80,7 +80,7 @@ class poweremail_core_accounts(osv.osv):
                         size=120, required=False,
                         readonly=True, states={'draft':[('readonly', False)]}),
         'smtppass': fields.char('Password',
-                        size=120, invisible=True,
-                        size=120, 
                       required=False, readonly=True,
                       states={'draft':[('readonly', False)]}),
       'smtptls':fields.boolean('Use TLS',

**Comment by sharoonthomas** [comment]
https://github.com/openlabs/poweremail/pull/27
