### ISSUE TITLE
send on create/update don't work

### ISSUE THREAD

**Issue by paulius-sladkevicius** [openlabs/poweremail#17]
To reporoduce this issue you need:
- Create template with "Send on create or "Send on update" options.
- Restart OpenERP server
- Try to create/write on the object on which is set template.

Email works till server restart. I think its related with https://github.com/openlabs/poweremail/blob/master/poweremail_template.py#L95 code, which don't register send_on_create and send_on_write methods.

Im using v6.0.3 OpenERP.

**Comment by sharoonthomas** [comment]
@komsas I have merged the patch by @and3p .

That should have solved this issue, can you confirm ?

**Comment by paulius-sladkevicius** [comment]
Sharoon, sorry forgot to close it. @and3p did this patch by my request.

**Comment by sharoonthomas** [comment]
@komsas @and3p Thanks for your contribution
