### ISSUE TITLE
Error when trying to enter at the mail box (web-client)

### ISSUE THREAD

**Issue by emedina77** [openlabs/poweremail#22]
Error message appears when trying to enter at the mail-box. 

The error only appears  using the web client, in GTK client i don't have any error and i can send an email.

I am using openerp V. 6.0.4.

Here is the log error:

<type 'exceptions.TypeError'>   Python 2.6.5: /usr/bin/python
Mon Mar 19 11:38:10 2012

A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.
 /usr/lib/pymodules/python2.6/cherrypy/_cprequest.py in respond(self=<cherrypy._cprequest.Request object>, path_info='/openerp/execute')
  604                     if self.handler:
  605                         self.stage = 'handler'
  606                         cherrypy.response.body = self.handler()
  607  
  608                     self.stage = 'before_finalize'
global cherrypy = <module 'cherrypy' from '/usr/lib/pymodules/python2.6/cherrypy/__init__.pyc'>, cherrypy.response = <cherrypy._ThreadLocalProxy object>, cherrypy.response.body = [], self = <cherrypy._cprequest.Request object>, self.handler = <cherrypy._cpdispatch.LateParamPageHandler object>
 /usr/lib/pymodules/python2.6/cherrypy/_cpdispatch.py in __call__(self=<cherrypy._cpdispatch.LateParamPageHandler object>)
   23     def **call**(self):
   24         try:
   25             return self.callable(_self.args, *_self.kwargs)
   26         except TypeError, x:
   27             test_callable_spec(self.callable, self.args, self.kwargs)
self = <cherrypy._cpdispatch.LateParamPageHandler object>, self.callable = <bound method Root.default of <openobject.controllers._root.Root object>>, self.args = ('openerp', 'execute'), self.kwargs = {'action': {'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, 'data': {'context': {'client': 'web', 'lang': u'es_MX', 'section_id': False, 'tz': False}, 'id': 398, 'ids': [398], 'model': 'ir.ui.menu', 'report_type': 'pdf'}, 'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'}
 /opt/openerp/web6/openobject/tools/_expose.py in func_wrapper(_args=(<openobject.controllers._root.Root object>, 'openerp', 'execute'), *_kw={'_': '1332178690019', 'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'})
  180                 raise cherrypy.HTTPError(405)
  181 
  182             res = func(_args, *_kw)
  183             if format == 'json' or (allow_json and 'allow_json' in cherrypy.request.params):
  184                 cherrypy.response.headers['Content-Type'] = 'text/javascript'
global res = '/opt/openerp/web6/openobject/controllers/templates/base.mako', func = <function default>, args = (<openobject.controllers._root.Root object>, 'openerp', 'execute'), kw = {'_': '1332178690019', 'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'}
 /opt/openerp/web6/openobject/controllers/_root.py in default(self=<openobject.controllers._root.Root object>, _args=('openerp', 'execute'), *_kw={'_': '1332178690019', 'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'})
   88             request.handler = cherrypy.NotFound()
   89 
   90         return request.handler()
   91 
   92     def find_handler(self):
request = <cherrypy._ThreadLocalProxy object>, request.handler = <cherrypy._cpdispatch.LateParamPageHandler object>
 /usr/lib/pymodules/python2.6/cherrypy/_cpdispatch.py in __call__(self=<cherrypy._cpdispatch.LateParamPageHandler object>)
   23     def **call**(self):
   24         try:
   25             return self.callable(_self.args, *_self.kwargs)
   26         except TypeError, x:
   27             test_callable_spec(self.callable, self.args, self.kwargs)
self = <cherrypy._cpdispatch.LateParamPageHandler object>, self.callable = <function index>, self.args = (), self.kwargs = {'action': {'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, 'data': {'context': {'client': 'web', 'lang': u'es_MX', 'section_id': False, 'tz': False}, 'id': 398, 'ids': [398], 'model': 'ir.ui.menu', 'report_type': 'pdf'}, 'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'}
 /opt/openerp/web6/addons/openerp/controllers/utils.py in wrapper(_args=(), *_kw={'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'})
  110             # User is logged in; allow access
  111             clear_login_fields(kw)
  112             return fn(_args, *_kw)
  113         else:
  114             action = kw.get('login_action', '')
fn = <bound method Execute.index of <openerp.controllers.execute.Execute object>>, args = (), kw = {'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'}
 /opt/openerp/web6/openobject/tools/_expose.py in func_wrapper(_args=(<openerp.controllers.execute.Execute object>,), *_kw={'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'})
  180                 raise cherrypy.HTTPError(405)
  181 
  182             res = func(_args, *_kw)
  183             if format == 'json' or (allow_json and 'allow_json' in cherrypy.request.params):
  184                 cherrypy.response.headers['Content-Type'] = 'text/javascript'
global res = '/opt/openerp/web6/openobject/controllers/templates/base.mako', func = <function index>, args = (<openerp.controllers.execute.Execute object>,), kw = {'payload': 'eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8'}
 /opt/openerp/web6/addons/openerp/controllers/execute.py in index(self=<openerp.controllers.execute.Execute object>, payload='eJxtUstqwzAQ_BWTixIwJhBakkAvPfTWWw-FNBjFWicCvdCj...IpXNIVA-8wmwkT2u1Wac9M9r6vJTEsHYEpOZGyH4YfgCoaPk8')
   17             zlib.decompress(
   18                 base64.urlsafe_b64decode(str(payload))))
   19         action, data = decoded_payload['action'], decoded_payload['data']
   20         cherrypy.request.params.update(decoded_payload)
   21         return actions.execute(action, **data)
global actions = <module 'openerp.controllers.actions' from '/opt...erp/web6/addons/openerp/controllers/actions.pyc'>, actions.execute = <function execute>, action = {'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, data = {'context': {'client': 'web', 'lang': u'es_MX', 'section_id': False, 'tz': False}, 'id': 398, 'ids': [398], 'model': 'ir.ui.menu', 'report_type': 'pdf'}
 /opt/openerp/web6/addons/openerp/controllers/actions.py in execute(action={'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, **data={'context': {'client': 'web', 'lang': u'es_MX', 'section_id': False, 'tz': False}, 'id': 398, 'ids': [398], 'limit': 20, 'model': 'ir.ui.menu', 'report_type': 'pdf', 'res_id': None, 'res_model': u'poweremail.mailbox', 'search_view': None, 'view_mode': u'tree,form', ...})
  393 
  394     action_executor = ACTIONS_BY_TYPE[action['type']]
  395     return action_executor(action, data)
  396 
  397 def execute_url(**data):
action_executor = <function act_window>, action = {'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, data = {'context': {'client': 'web', 'lang': u'es_MX', 'section_id': False, 'tz': False}, 'id': 398, 'ids': [398], 'limit': 20, 'model': 'ir.ui.menu', 'report_type': 'pdf', 'res_id': None, 'res_model': u'poweremail.mailbox', 'search_view': None, 'view_mode': u'tree,form', ...}
 /opt/openerp/web6/addons/openerp/controllers/actions.py in act_window(action={'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, data={'context': {'client': 'web', 'lang': u'es_MX', 'section_id': False, 'tz': False}, 'id': 398, 'ids': [398], 'limit': 20, 'model': 'ir.ui.menu', 'report_type': 'pdf', 'res_id': None, 'res_model': u'poweremail.mailbox', 'search_view': None, 'view_mode': u'tree,form', ...})
  273                           context_menu=data.get('context_menu'),
  274                           display_menu_tip=display_menu_tip,
  275                           action_id=action.get('id'))
  276 
  277 def server(action, data):
action_id undefined, action = {'auto_refresh': 0, 'auto_search': True, 'context': u"{'company':True}", 'display_menu_tip': True, 'domain': u"[('folder','=','outbox')]", 'filter': False, 'groups_id': [], 'help': False, 'id': 590, 'limit': 80, ...}, action.get = <built-in method get of dict object>
 /opt/openerp/web6/addons/openerp/controllers/actions.py in execute_window(view_ids=[906, False], model=u'poweremail.mailbox', res_id=None, domain=[('folder', '=', 'outbox')], view_type=u'form', context={'_terp_view_name': u'Buz\xf3n de correo', 'active_id': 398, 'active_ids': [398], 'active_model': 'ir.ui.menu', 'client': 'web', 'company': True, 'lang': u'es_MX', 'section_id': False, 'tz': False}, mode=[u'tree', u'form'], name=u'Buz\xf3n de correo', target=u'current', limit=20, search_view=None, context_menu=None, display_menu_tip=False, action_id=590)
   87         params.view_mode=mode
   88 
   89         return Form().create(params)
   90 
   91     elif view_type == 'tree':
global Form = <class 'openerp.controllers.form.Form'>, ).create = <unbound method Form.create>, params = {'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}
 /opt/openerp/web6/addons/openerp/controllers/utils.py in wrapper(_args=({'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None},), *_kw={})
  110             # User is logged in; allow access
  111             clear_login_fields(kw)
  112             return fn(_args, *_kw)
  113         else:
  114             action = kw.get('login_action', '')
fn = <bound method Form.create of <openerp.controllers.form.Form object>>, args = ({'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None},), kw = {}
 /opt/openerp/web6/openobject/tools/_expose.py in func_wrapper(_args=(<openerp.controllers.form.Form object>, {'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}), *_kw={})
  180                 raise cherrypy.HTTPError(405)
  181 
  182             res = func(_args, *_kw)
  183             if format == 'json' or (allow_json and 'allow_json' in cherrypy.request.params):
  184                 cherrypy.response.headers['Content-Type'] = 'text/javascript'
global res = '/opt/openerp/web6/openobject/controllers/templates/base.mako', func = <function create>, args = (<openerp.controllers.form.Form object>, {'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}), kw = {}
 /opt/openerp/web6/addons/openerp/controllers/form.py in create(self=<openerp.controllers.form.Form object>, params={'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, tg_errors=None)
  193         if params.view_type == 'tree':
  194             params.editable = True
  195         form = self.create_form(params, tg_errors)
  196 
  197         if not tg_errors:
form undefined, self = <openerp.controllers.form.Form object>, self.create_form = <bound method Form.create_form of <openerp.controllers.form.Form object>>, params = {'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, tg_errors = None
 /opt/openerp/web6/addons/openerp/controllers/form.py in create_form(self=<openerp.controllers.form.Form object>, params={'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, tg_errors=None)
  184         params.view_type = params.view_type or params.view_mode[0]
  185 
  186         return tw.form_view.ViewForm(params, name="view_form", action="/openerp/form/save")
  187 
  188     @expose(template="/openerp/controllers/templates/form.mako")
global tw = <module 'openerp.widgets' from '/opt/openerp/web6/addons/openerp/widgets/__init__.pyc'>, tw.form_view = <module 'openerp.widgets.form_view' from '/opt/openerp/web6/addons/openerp/widgets/form_view.pyc'>, tw.form_view.ViewForm = <class 'openerp.widgets.form_view.ViewForm'>, params = {'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, name undefined, action undefined
 /opt/openerp/web6/addons/openerp/widgets/form_view.py in __init__(self=ViewForm, params={'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, **kw={'action': '/openerp/form/save', 'name': 'view_form'})
   88  
   89         self.screen = Screen(prefix='', hastoolbar=True, hassubmenu=True, editable=editable, readonly=readonly,
   90                              selectable=params.selectable or 2)
   91 
   92         if self.screen.widget and self.screen.view_type in ['form', 'tree']:
selectable undefined, params = {'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, params.selectable = None
 /opt/openerp/web6/addons/openerp/widgets/screen.py in __init__(self=Screen, params={'_terp_action_id': 590, '_terp_view_type': u'tr...rp_view_ids': [906, False], 'context_menu': None}, prefix='', name='', views_preloaded={}, hastoolbar=True, hassubmenu=True, editable=True, readonly=False, selectable=2, nolinks=1, **kw={})
  105         self.kalendar           = params.kalendar
  106         if self.view_mode:
  107             self.add_view_id(self.view_id, self.view_type)
  108 
  109     def add_view_id(self, view_id, view_type):
self = Screen, self.add_view_id = <bound method Screen.add_view_id of Screen>, self.view_id = 906, self.view_type = u'tree'
 /opt/openerp/web6/addons/openerp/widgets/screen.py in add_view_id(self=Screen, view_id=906, view_type=u'tree')
  122             view = cache.fields_view_get(self.model, view_id or False, view_type, ctx, self.hastoolbar, self.hassubmenu)
  123 
  124         self.add_view(view, view_type)
  125 
  126     def add_view(self, view, view_type='form'):
self = Screen, self.add_view = <bound method Screen.add_view of Screen>, view = {'arch': u'<tree string="Bandeja de Salida">\n<field name="p...2"/>\n<field name="pem_recd" colspan="2"/>\n</tree>', 'field_parent': False, 'fields': {'date_mail': {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}, 'pem_attachments_ids': {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}, 'pem_from': {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}, 'pem_recd': {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}}, 'pem_subject': {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}, 'pem_user': {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}}, 'model': u'poweremail.mailbox', 'name': u'poweremail.mailbox.outboxtree', 'submenu': False, 'toolbar': {'action': [], 'print': [], 'relate': []}, 'type': u'tree', 'view_id': 906}, view_type = u'tree'
 /opt/openerp/web6/addons/openerp/widgets/screen.py in add_view(self=Screen, view={'arch': u'<tree string="Bandeja de Salida">\n<field name="p...2"/>\n<field name="pem_recd" colspan="2"/>\n</tree>', 'field_parent': False, 'fields': {'date_mail': {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}, 'pem_attachments_ids': {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}, 'pem_from': {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}, 'pem_recd': {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}}, 'pem_subject': {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}, 'pem_user': {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}}, 'model': u'poweremail.mailbox', 'name': u'poweremail.mailbox.outboxtree', 'submenu': False, 'toolbar': {'action': [], 'print': [], 'relate': []}, 'type': u'tree', 'view_id': 906}, view_type=u'tree')
  130  
  131         from _views import get_view_widget
  132         self.widget = get_view_widget(view_type, self)
  133 
  134         self.string = (self.widget or '') and self.widget.string
self = Screen, self.widget = None, get_view_widget = <function get_view_widget>, view_type = u'tree'
 /opt/openerp/web6/addons/openerp/widgets/_views.py in get_view_widget(kind=u'tree', screen=Screen)
  138         raise Exception("view '%s' not supported." % kind)
  139 
  140     return view(screen)
  141 
  142 def get_registered_views():
view = <openerp.widgets._views.ListView object>, screen = Screen
 /opt/openerp/web6/addons/openerp/widgets/_views.py in __call__(self=<openerp.widgets._views.ListView object>, screen=Screen)
  119                                     count=screen.count, nolinks=screen.link,
  120                                     m2m=screen.m2m, o2m=screen.o2m,
  121                                     default_data=screen.default_value)
  122 
  123         screen.ids = widget.ids
default_data undefined, screen = Screen, screen.default_value = []
 /opt/openerp/web6/addons/openerp/widgets/listgrid.py in **init**(self=List, name='_terp_list', model=u'poweremail.mailbox', view={'arch': u'<tree string="Bandeja de Salida">\n<field name="p...2"/>\n<field name="pem_recd" colspan="2"/>\n</tree>', 'field_parent': False, 'fields': {'date_mail': {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}, 'pem_attachments_ids': {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}, 'pem_from': {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}, 'pem_recd': {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}}, 'pem_subject': {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}, 'pem_user': {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}}, 'model': u'poweremail.mailbox', 'name': u'poweremail.mailbox.outboxtree', 'submenu': False, 'toolbar': {'action': [], 'print': [], 'relate': []}, 'type': u'tree', 'view_id': 906}, ids=[], domain=[('folder', '=', 'outbox')], context={'_terp_view_name': u'Buz\xf3n de correo', 'active_id': 398, 'active_ids': [398], 'active_model': 'ir.ui.menu', 'client': 'web', 'company': True, 'lang': u'es_MX', 'section_id': False, 'tz': False}, **kw={'count': 0, 'default_data': [], 'editable': True, 'limit': 20, 'm2m': 0, 'nolinks': 1, 'o2m': 0, 'offset': 0, 'selectable': 2, 'view_mode': [u'tree', u'form']})
  248 
  249         self.values = copy.deepcopy(data)
  250         self.headers, self.hiddens, self.data, self.field_total, self.buttons = self.parse(root, fields, data)
  251 
  252         for k, v in self.field_total.items():
self = List, self.headers = None, self.hiddens = [], self.data = None, self.field_total = {}, self.buttons = [], self.parse = <bound method List.parse of List>, root = <DOM Element: tree>, fields = {'date_mail': {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}, 'pem_attachments_ids': {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}, 'pem_from': {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}, 'pem_recd': {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}}, 'pem_subject': {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}, 'pem_user': {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}}, data = []
 /opt/openerp/web6/addons/openerp/widgets/listgrid.py in parse(self=List, root=<DOM Element: tree>, fields={'date_mail': {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}, 'pem_attachments_ids': {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}, 'pem_from': {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}, 'pem_recd': {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}}, 'pem_subject': {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}, 'pem_user': {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}}, data=[])
  456                     headers += [(name, fields[name])]
  457 
  458         dataset = ListViewDataSet(data, list_fields, self.colors)
  459 
  460         return headers, hiddens, dataset, field_total, buttons
dataset undefined, global ListViewDataSet = <class 'openerp.widgets.listgrid.ListViewDataSet'>, data = [], list_fields = [(u'pem_user', u'many2one', False, {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}), (u'pem_from', u'char', False, {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}), (u'pem_subject', u'char', False, {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}), (u'pem_attachments_ids', u'many2many', False, {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}), (u'date_mail', u'datetime', False, {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}), (u'pem_recd', u'char', False, {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}})], self = List, self.colors = {}
 /opt/openerp/web6/addons/openerp/widgets/listgrid.py in __init__(self=<openerp.widgets.listgrid.ListViewDataSet object>, data=[], fields=[(u'pem_user', u'many2one', False, {'context': {}, 'digits': (16, 2), 'domain': [], 'fnct_inv': u'_fnct_write', 'fnct_inv_arg': (u'pem_account_id', u'user'), 'fnct_search': u'_fnct_search', 'func_method': True, 'func_obj': u'res.users', 'function': u'_fnct_read', 'name': u'pem_user', ...}), (u'pem_from', u'char', False, {'name': u'pem_from', 'select': u'1', 'selectable': True, 'size': 64, 'string': u'Desde', 'type': u'char', 'views': {}}), (u'pem_subject', u'char', False, {'name': u'pem_subject', 'select': u'1', 'selectable': True, 'size': 200, 'string': u'Asunto', 'type': u'char', 'views': {}}), (u'pem_attachments_ids', u'many2many', False, {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}), (u'date_mail', u'datetime', False, {'name': u'date_mail', 'select': u'2', 'selectable': True, 'string': u'Fecha recepci\xf3n/env\xedo', 'type': u'datetime', 'views': {}}), (u'pem_recd', u'char', False, {'colspan': u'2', 'name': u'pem_recd', 'selectable': True, 'size': 50, 'string': u'Recibido el', 'type': u'char', 'views': {}})], colors={})
   49                 cell = Hidden(**attrs)
   50             else:
   51                 cell = CELLTYPES[kind](value=False, **attrs)
   52             self.fields_obj.append((name, invisible, cell))
   53 
cell = Char, global CELLTYPES = {'boolean': <class 'openerp.widgets.listgrid.Boolean'>, 'char': <class 'openerp.widgets.listgrid.Char'>, 'date': <class 'openerp.widgets.listgrid.DateTime'>, 'datetime': <class 'openerp.widgets.listgrid.DateTime'>, 'float': <class 'openerp.widgets.listgrid.Float'>, 'float_time': <class 'openerp.widgets.listgrid.FloatTime'>, 'integer': <class 'openerp.widgets.listgrid.Int'>, 'many2many': <class 'openerp.widgets.listgrid.M2M'>, 'many2one': <class 'openerp.widgets.listgrid.M2O'>, 'one2many': <class 'openerp.widgets.listgrid.O2M'>, ...}, kind = u'many2many', value undefined, builtin False = False, attrs = {'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...}
 /opt/openerp/web6/addons/openerp/widgets/listgrid.py in __init__(self=M2M, **attrs={'context': {}, 'domain': [], 'name': u'pem_attachments_ids', 'related_columns': [u'mail_id', u'att_id'], 'relation': u'ir.attachment', 'select': u'2', 'selectable': True, 'string': u'Adjuntos', 'third_table': u'mail_attachments_rel', 'type': u'many2many', ...})
  471         self.attrs = attrs.copy()
  472 
  473         self.text = self.get_text()
  474         self.link = self.get_link()
  475 
self = M2M, self.text = None, self.get_text = <bound method M2M.get_text of M2M>
 /opt/openerp/web6/addons/openerp/widgets/listgrid.py in get_text(self=M2M)
  526 
  527     def get_text(self):
  528         return "(%d)" % len(self.value)
  529 
  530 class Selection(Char):
builtin len = <built-in function len>, self = M2M, self.value = False

<type 'exceptions.TypeError'>: object of type 'bool' has no len()
      args = ("object of type 'bool' has no len()",)
      message = "object of type 'bool' has no len()"

**Comment by shalabhaggarwal** [comment]
This seems to be a bug with web client of openerp.
