### ISSUE TITLE
SMTP Out going connection test failed encoding problem

### ISSUE THREAD

**Issue by jcharton** [openlabs/poweremail#25]
Hi. I work under openerp 6.1, I wanted to install your module to handle staff emails.
But when I want to try the out going server it fails:

Out going connection test failed

Reason: 'bool' object has no attribute 'encode' 

Can you help me ? Thanks in advance.

**Comment by shalabhaggarwal** [comment]
@jcharton Can you provide the complete stack trace for the error?

**Comment by shalabhaggarwal** [comment]
Hi @jcharton 

Can you please test with https://github.com/shalabhaggarwal/poweremail and let us know if it fixes the issue for you?

Thanks

**Comment by jcharton** [comment]
Hi shalabhaggarwal.

Sorry I did not answer sooner, but I had no time to test before.
It's working.
Thanks a lot!
