### ISSUE TITLE
HTML View

### ISSUE THREAD

**Issue by DaSpawn** [openlabs/poweremail#31]
I have installed Poweremail in OpenERP 6.1 pulled from latest code, and it is working properly.  In the web interface there is 2 tabs when viewing email, Standard Body (Text) and Body (HTML-Web Client Only).  The HTMl version currently shows the HTML source code instead of the actual rendered page.  
1. How can I get the HTML to display rendered
2. Is it possible to show the HTML version first, 
3. is it possible hide the HTML version if there is only a text version of the message and vice versa

Thanks

**Comment by sharoonthomas** [comment]
There was a html view for OpenERP. I am not sure if it still exists. If it does and it works, will be happy to merge your pull request.

However, i will wait for two more people to confirm that it works well.

Remember, that the widget should not be used with the template editor, but only with the email message view.
