### ISSUE TITLE
Error when I send with attachments

### ISSUE THREAD

**Issue by JuanjoA** [openlabs/poweremail#4]
I am trying to use power mail to send quotation to the customers. However when I press "Quotation Mail Form" it shows the error:

"The operation cannot be completed, probably due to the following: - deletion: you may be trying to delete a record while other records still reference it - creation/update: a mandatory field is not correctly set [object with reference: email_template_mailbox - email.template.mailbox]". 

I am able to send mail without attachment but receive this error with attachments. Kindly let me know what I am doing wrong and how to resolve this.

Thx

**Comment by tarasiadis** [comment]
I have the same problem

**Comment by ghost** [comment]
Looking issue .

**Comment by prakharbansal** [comment]
We were not able to replicate the issue. Please update your code to the latest dev branch. This ticket is being closed as of now. In case you face the issue again, then please open a new ticket and also let us know the steps taken by you while facing this error.
