### ISSUE TITLE
unable to install the module

### ISSUE THREAD

**Issue by edg1** [openlabs/poweremail#5]
The module will not install.. 
we have put the files in addon directory.
we have tried to upload via the client uploader
there are no error logs.
 any help ?

**Comment by sharoonthomas** [comment]
Can you try with the dev branch and see if the issue persists

https://github.com/openlabs/poweremail/tarball/dev

**Comment by sharoonthomas** [comment]
Closing the issue as there has been no update and others seem to be able to use,
